#!/usr/bin/env python3
"""
Member 1 Validation Helper - Compare Assembly Outputs with Reference

Usage:
    python3 validate_layers.py --layer hilbert --asm-output output.bin
    python3 validate_layers.py --layer linear --asm-output output.bin
    python3 validate_layers.py --all

This script loads reference outputs generated by generate_validation_data.py
and compares them with actual assembly outputs from VeeR-iSS.
"""

import numpy as np
import argparse
from pathlib import Path
import sys


def compute_metrics(reference, actual):
    """Compute MSE, MAE, max absolute error."""
    diff = reference - actual
    mse = np.mean(diff ** 2)
    mae = np.mean(np.abs(diff))
    max_ae = np.max(np.abs(diff))
    return mse, mae, max_ae


def validate_hilbert(asm_output_file):
    """Validate Hilbert Scan layer."""
    print("\n" + "="*70)
    print("VALIDATING: Hilbert Scan")
    print("="*70)
    
    ref_file = "validation_data/hilbert_output_ref.npy"
    
    # Load reference
    if not Path(ref_file).exists():
        print(f"✗ Reference file not found: {ref_file}")
        return False
    
    reference = np.load(ref_file)
    print(f"✓ Loaded reference: shape {reference.shape}, dtype {reference.dtype}")
    
    # Load assembly output
    if not Path(asm_output_file).exists():
        print(f"✗ Assembly output file not found: {asm_output_file}")
        return False
    
    # Assume binary float32 format
    actual = np.fromfile(asm_output_file, dtype=np.float32)
    actual = actual.reshape(reference.shape)
    print(f"✓ Loaded assembly output: shape {actual.shape}, dtype {actual.dtype}")
    
    # Compute metrics
    mse, mae, max_ae = compute_metrics(reference, actual)
    
    # Threshold: MSE < 1e-12 (exact match expected)
    threshold = 1e-12
    passed = mse < threshold
    
    print(f"\nMetrics:")
    print(f"  MSE: {mse:.2e} (threshold: {threshold:.2e})")
    print(f"  MAE: {mae:.2e}")
    print(f"  Max Absolute Error: {max_ae:.2e}")
    print(f"\nResult: {'✓ PASS' if passed else '✗ FAIL'}")
    
    return passed


def validate_linear(asm_output_file):
    """Validate Linear Layer."""
    print("\n" + "="*70)
    print("VALIDATING: Linear Layer")
    print("="*70)
    
    ref_file = "validation_data/linear_output_ref.npy"
    
    # Load reference
    if not Path(ref_file).exists():
        print(f"✗ Reference file not found: {ref_file}")
        return False
    
    reference = np.load(ref_file)
    print(f"✓ Loaded reference: shape {reference.shape}, dtype {reference.dtype}")
    
    # Load assembly output
    if not Path(asm_output_file).exists():
        print(f"✗ Assembly output file not found: {asm_output_file}")
        return False
    
    actual = np.fromfile(asm_output_file, dtype=np.float32)
    actual = actual.reshape(reference.shape)
    print(f"✓ Loaded assembly output: shape {actual.shape}, dtype {actual.dtype}")
    
    # Compute metrics
    mse, mae, max_ae = compute_metrics(reference, actual)
    
    # Threshold: MSE < 1e-6 (float32 precision)
    threshold = 1e-6
    passed = mse < threshold
    
    print(f"\nMetrics:")
    print(f"  MSE: {mse:.2e} (threshold: {threshold:.2e})")
    print(f"  MAE: {mae:.2e}")
    print(f"  Max Absolute Error: {max_ae:.2e}")
    print(f"\nResult: {'✓ PASS' if passed else '✗ FAIL'}")
    
    return passed


def validate_tlts(asm_output_file):
    """Validate Take Last Timestep layer."""
    print("\n" + "="*70)
    print("VALIDATING: Take Last Timestep")
    print("="*70)
    
    ref_file = "validation_data/tlts_output_ref.npy"
    
    # Load reference
    if not Path(ref_file).exists():
        print(f"✗ Reference file not found: {ref_file}")
        return False
    
    reference = np.load(ref_file)
    print(f"✓ Loaded reference: shape {reference.shape}, dtype {reference.dtype}")
    
    # Load assembly output
    if not Path(asm_output_file).exists():
        print(f"✗ Assembly output file not found: {asm_output_file}")
        return False
    
    actual = np.fromfile(asm_output_file, dtype=np.float32)
    actual = actual.reshape(reference.shape)
    print(f"✓ Loaded assembly output: shape {actual.shape}, dtype {actual.dtype}")
    
    # Compute metrics
    mse, mae, max_ae = compute_metrics(reference, actual)
    
    # Threshold: MSE < 1e-12 (exact match)
    threshold = 1e-12
    passed = mse < threshold
    
    print(f"\nMetrics:")
    print(f"  MSE: {mse:.2e} (threshold: {threshold:.2e})")
    print(f"  MAE: {mae:.2e}")
    print(f"  Max Absolute Error: {max_ae:.2e}")
    print(f"\nResult: {'✓ PASS' if passed else '✗ FAIL'}")
    
    return passed


def validate_softmax(asm_output_file):
    """Validate Softmax layer."""
    print("\n" + "="*70)
    print("VALIDATING: Softmax")
    print("="*70)
    
    ref_file = "validation_data/softmax_output_ref.npy"
    
    # Load reference
    if not Path(ref_file).exists():
        print(f"✗ Reference file not found: {ref_file}")
        return False
    
    reference = np.load(ref_file)
    print(f"✓ Loaded reference: shape {reference.shape}, dtype {reference.dtype}")
    
    # Load assembly output
    if not Path(asm_output_file).exists():
        print(f"✗ Assembly output file not found: {asm_output_file}")
        return False
    
    actual = np.fromfile(asm_output_file, dtype=np.float32)
    actual = actual.reshape(reference.shape)
    print(f"✓ Loaded assembly output: shape {actual.shape}, dtype {actual.dtype}")
    
    # Check sum constraint
    actual_sum = np.sum(actual)
    sum_check = abs(actual_sum - 1.0) < 1e-6
    
    print(f"\nSum Check (probabilities should sum to 1.0):")
    print(f"  Reference sum: {np.sum(reference):.10f}")
    print(f"  Actual sum: {actual_sum:.10f}")
    print(f"  Sum error: {abs(actual_sum - 1.0):.2e}")
    print(f"  Sum OK: {'✓ YES' if sum_check else '✗ NO'}")
    
    # Compute metrics
    mse, mae, max_ae = compute_metrics(reference, actual)
    
    # Threshold: MSE < 1e-6 (float32 precision)
    threshold = 1e-6
    passed = (mse < threshold) and sum_check
    
    print(f"\nMetrics:")
    print(f"  MSE: {mse:.2e} (threshold: {threshold:.2e})")
    print(f"  MAE: {mae:.2e}")
    print(f"  Max Absolute Error: {max_ae:.2e}")
    print(f"\nResult: {'✓ PASS' if passed else '✗ FAIL'}")
    
    return passed


def main():
    parser = argparse.ArgumentParser(
        description="Validate Member 1 Assembly Layer Implementations"
    )
    parser.add_argument(
        "--layer",
        choices=["hilbert", "linear", "tlts", "softmax"],
        help="Layer to validate"
    )
    parser.add_argument(
        "--asm-output",
        help="Path to assembly output binary file"
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Validate all layers (requires all outputs in validation_data/)"
    )
    
    args = parser.parse_args()
    
    if args.all:
        print("\n" + "="*70)
        print("MEMBER 1 LAYER VALIDATION (ALL LAYERS)")
        print("="*70)
        
        # Quick check - assumes reference files exist
        results = []
        
        # These would need separate output files from VeeR-iSS
        print("\n⚠ Note: For full validation, you need to:")
        print("  1. Run each assembly layer on VeeR-iSS")
        print("  2. Save outputs to binary files")
        print("  3. Re-run with --layer and --asm-output flags")
        print("\nExample:")
        print("  python3 validate_layers.py --layer hilbert --asm-output hilbert_out.bin")
        
        return 0
    
    if not args.layer or not args.asm_output:
        parser.print_help()
        return 1
    
    # Route to appropriate validator
    validators = {
        "hilbert": validate_hilbert,
        "linear": validate_linear,
        "tlts": validate_tlts,
        "softmax": validate_softmax,
    }
    
    validator = validators[args.layer]
    passed = validator(args.asm_output)
    
    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
